name: test by marker name

on:
  workflow_dispatch:
    inputs:
      runenv:
        description: Select the env to run
        required: true
        default: dev
        type: choice
        options:
          - dev
          - staging
          - prod

env:
  MAXFAIL: 5
  RETENTION_DAYS: 7

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Checking input
        run: job 1 on ${{ inputs.runenv }} 
  job-2:
    runs-on: ubuntu-latest
    steps:
      - name: Checking input
        run: job 2 on ${{ inputs.runenv }} 
  job-3:
    runs-on: ubuntu-latest
    steps:
      - name: Checking input
        run: job 3 on ${{ inputs.runenv }} 