name: test by marker name

on:
  workflow_dispatch:
    inputs:
      test-name:
        description: Select the test name
        required: true
        default: ""
        type: choice
        options:
          - job1
          - job2
          - job3
      runenv:
        description: Select the env to run
        required: true
        default: dev
        type: choice
        options:
          - dev
          - staging
          - prod

env:
  MAXFAIL: 5
  RETENTION_DAYS: 7

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Job-1 test
        if: ${{ inputs.test-name }} == "job1"
        run: echo ${{ inputs.test-name }} on ${{ inputs.runenv }} 
      - name: Job-2 test
        if: ${{ inputs.test-name }} == "job2"
        run: echo ${{ inputs.test-name }} on ${{ inputs.runenv }} 
      - name: Job-3 test
        if: ${{ inputs.test-name }} == "job3"
        run: echo ${{ inputs.test-name }} on ${{ inputs.runenv }} 