name: test by marker name

on:
  workflow_dispatch:
    inputs:
      test-name:
        description: Select the test name
        required: true
        type: choice
        options:
          - job-1
          - job-2
          - job-3
      runenv:
        description: Select the env to run
        required: true
        default: dev
        type: choice
        options:
          - dev
          - staging
          - prod

env:
  TESTING_VARS: .github/workflows/env-vars

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Load environment variables
        run: |
          cat $TESTING_VARS 
          source "$TESTING_VARS"
      - name: Job-1 test
        if: ${{ github.event.inputs.test-name == 'job-1' }}
        run: echo ${{ inputs.test-name }} on ${{ inputs.runenv }} accessing $AGE $RETENTION_DAYS
      - name: Job-2 test
        if: ${{ github.event.inputs.test-name == 'job-2' }}
        run: echo ${{ inputs.test-name }} on ${{ inputs.runenv }} 
      - name: Job-3 test
        if: ${{ github.event.inputs.test-name == 'job-3' }}
        run: echo ${{ inputs.test-name }} on ${{ inputs.runenv }} 
      - name: Save Report Artifacts
        if: always()
        run: echo Reports saved